language: perl

perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

env:
    - "HARNESS_OPTIONS=j9"

install:
    - "cpanm -M https://cpan.metacpan.org -n --installdeps ."

notifications:
    email: false
